/*
 * Copyright (C) 2023 Goldsmiths, University of London.
 * All rights reserved.
 */

import { Database } from 'better-sqlite3';
import { insertModules } from '../../utils/insert_modules';

const upSql = `
CREATE TABLE modules(
    id INTEGER PRIMARY KEY,
    name TEXT,
    code TEXT,
    enabled BOOLEAN DEFAULT TRUE,
    grades TEXT DEFAULT NULL
);

ALTER TABLE pages
    ADD COLUMN module INTEGER DEFAULT NULL REFERENCES modules(id);
`;

const downSql = `
BEGIN IMMEDIATE;

-- Drop autogenerated pages to prevent confusion when upgrading back up
DELETE FROM pages WHERE module NOTNULL;

ALTER TABLE pages DROP COLUMN module;
DROP TABLE modules;

COMMIT;
`;

export default {
    up(db: Database) {
        db.exec('BEGIN IMMEDIATE;');
        db.exec(upSql);
        insertModules(db);
        db.exec('COMMIT;');
    },
    down(db: Database) {
        db.exec(downSql);
    },
};
