import { Database } from 'better-sqlite3';
import { insertModules } from '../../utils/insert_modules';

const upSql = `
SAVEPOINT 20230807_add_modules_alter_schema;

CREATE TABLE modules(
    id INTEGER PRIMARY KEY,
    name TEXT,
    code TEXT,
    enabled BOOLEAN DEFAULT TRUE,
    grades TEXT,
    page INTEGER
);

ALTER TABLE pages
    ADD COLUMN module INTEGER DEFAULT NULL REFERENCES modules(id);

RELEASE 20230807_add_modules_alter_schema;
`;

const downSql = `
BEGIN IMMEDIATE;

-- Drop autogenerated pages to prevent confusion when upgrading back up
DELETE FROM pages WHERE module NOTNULL;

ALTER TABLE pages DROP COLUMN module;
DROP TABLE modules;

COMMIT;
`;

export default {
    up(db: Database) {
        db.exec('BEGIN IMMEDIATE;');
        db.exec(upSql);
        insertModules(db);
        db.exec('COMMIT;');
    },
    down(db: Database) {
        db.exec(downSql);
    },
};
