const modules = [
    { name: 'Introduction to Programming I', code: 'CM1005' },
    { name: 'Introduction to Programming II', code: 'CM1010' },
    { name: 'Computational Mathematic', code: 'CM1015' },
    { name: 'Discrete Mathematics', code: 'CM1020' },
    { name: 'Fundamentals of Computer Science', code: 'CM1025' },
    { name: 'How Computers Work', code: 'CM1030' },
    { name: 'Algorithms and Data Structures I', code: 'CM1035' },
    { name: 'Web Development', code: 'CM1040' },
    { name: 'Object Oriented Programming', code: 'CM2005' },
    { name: 'Software Design and Development', code: 'CM2010' },
    { name: 'Programming with Data', code: 'CM2015' },
    { name: 'Agile Software Projects', code: 'CM2020' },
    { name: 'Computer Security', code: 'CM2025' },
    { name: 'Graphics Programming', code: 'CM2030' },
    { name: 'Algorithms and Data Structures II', code: 'CM2035' },
    { name: 'Databases, Networks and the Web', code: 'CM2040' },
    { name: 'Data Science', code: 'CM3005' },
    { name: 'Databases and Advanced Data Techniques', code: 'CM3010' },
    { name: 'Machine Learning and Neural Networks', code: 'CM3015' },
    { name: 'Artificial Intelligence  ', code: 'CM3020' },
    { name: 'Virtual Reality', code: 'CM3025' },
    { name: 'Games Development', code: 'CM3030' },
    { name: 'Advanced Web Development', code: 'CM3035' },
    { name: 'Physical Computing and Internet of Things', code: 'CM3040' },
    { name: '3D Graphics and Animation', code: 'CM3045' },
    { name: 'Mobile Development', code: 'CM3050' },
    { name: 'Interaction Design', code: 'CM3055' },
    { name: 'Natural Language Processing', code: 'CM3060' },
    { name: 'Intelligent Signal Processing', code: 'CM3065' },
    { name: 'Final Project', code: 'CM3070' },
];

export default modules;
