name: test
run-name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install and set up dependencies
        run: |
          yarn install

      - name: Run unit tests
        run: |
          yarn run vitest run
